# documentation: https://your-app-documentation-url
# slogan: Your application slogan here
# tags: your,app,tags,here
# logo: svgs/your-logo.svg
# port: 3000

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_APP_3000
      - NODE_ENV=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - TRAEFIK_USER=${TRAEFIK_USER:-admin}
      - TRAEFIK_PASSWORD_HASH=${TRAEFIK_PASSWORD_HASH}
    labels:
      - "traefik.http.middlewares.bolt-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}"
    volumes:
      - app-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5173"]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  app-data:
